"use client"

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog"
import { AgentChart } from "@/components/agent-chart"
import { BarChart3, Lightbulb, Info } from "lucide-react"

interface ChartData {
  id: string
  type: "line" | "bar" | "pie" | "area" | "scatter"
  title: string
  data: {
    data: any[]
    xAxisKey?: string
    yAxisKey?: string
  }
  justification?: string
}

interface AgentResponse {
  analysis: string
  justification: string
  chart?: ChartData
  success: boolean
}

interface AgentResponseModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  response: AgentResponse | null
}

export function AgentResponseModal({ open, onOpenChange, response }: AgentResponseModalProps) {
  if (!response) return null

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-5xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="text-2xl font-bold">
            Financial Analysis
          </DialogTitle>
          <DialogDescription>
            AI-powered insights based on your transaction data
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6 p-6">
          {/* Chart Section */}
          {response.chart && (
            <div className="space-y-4">
              <div className="flex items-center gap-2 text-lg font-semibold">
                <BarChart3 className="h-5 w-5 text-primary" />
                <span>{response.chart.title}</span>
              </div>
              
              <div className="rounded-lg border border-border bg-card p-4">
                <AgentChart
                  type={response.chart.type}
                  title={response.chart.title}
                  data={response.chart.data}
                />
              </div>

              {/* Chart Justification */}
              {response.chart.justification && (
                <div className="rounded-lg border border-blue-200 bg-blue-50/50 dark:border-blue-800 dark:bg-blue-950/20 p-4">
                  <div className="flex items-start gap-3">
                    <Info className="h-5 w-5 text-blue-600 flex-shrink-0 mt-0.5" />
                    <div className="flex-1">
                      <div className="text-sm font-medium text-card-foreground mb-2">
                        Why This Chart?
                      </div>
                      <div className="text-sm text-muted-foreground leading-relaxed">
                        {response.chart.justification}
                      </div>
                    </div>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Analysis Section */}
          <div className="space-y-3">
            <div className="flex items-center gap-2 text-lg font-semibold">
              <Lightbulb className="h-5 w-5 text-amber-600" />
              <span>Detailed Analysis</span>
            </div>
            
            <div className="rounded-lg border border-border bg-secondary/30 p-4">
              <div className="text-sm text-card-foreground leading-relaxed whitespace-pre-wrap">
                {response.analysis}
              </div>
            </div>
          </div>

          {/* Justification Section */}
          {response.justification && (
            <div className="space-y-3">
              <div className="flex items-center gap-2 text-lg font-semibold">
                <Info className="h-5 w-5 text-green-600" />
                <span>Analysis Methodology</span>
              </div>
              
              <div className="rounded-lg border border-green-200 bg-green-50/50 dark:border-green-800 dark:bg-green-950/20 p-4">
                <div className="text-sm text-muted-foreground leading-relaxed whitespace-pre-wrap">
                  {response.justification}
                </div>
              </div>
            </div>
          )}

          {/* Disclaimer */}
          <div className="rounded-lg border border-muted bg-muted/30 p-3">
            <p className="text-xs text-muted-foreground text-center">
              This analysis is generated by AI and should be used as a guide. Please consult with a financial advisor for personalized advice.
            </p>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
